### ISSUE TITLE
Wrong deduplication with the same hostname but different groupname

### ISSUE THREAD

**Issue by proffust** [alerta/alerta#1005]
**Issue Summary**
Wrong deduplication with the same hostname

**Environment**
- OS: Linux
- API version: 7.2.10
- Deployment: Docker

- Database: MongoDB

- Server config:
  Auth enabled? No

- web UI version: 7.2.10
- CLI version: 7.2.10

**To Reproduce**
1. Create in prometheus alert
```
- name: targets
  rules:
    - alert: monitor_service_down
      expr: up == 0
      for: 30s
      labels:
        severity: critical
        service: prometheus
        environment: Production
      annotations:
        summary: "Monitor service non-operational"
        description: "Service {{ $labels.instance }}, job {{ $labels.job }} is down."
```
2. Create route in alertmanager
```
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 1h
  receiver: alerta

  routes:
  - match_re:
      job: '.+'
    receiver: alerta

receivers:
- name: "alerta"
  webhook_configs:
  - url: 'http://alerta-web:8080/alerta/api/webhooks/prometheus?api-key='
    send_resolved: true

```
3. Alert go to firing, in prometheus:
![image](https://user-images.githubusercontent.com/33157540/59770512-d5c70480-92b0-11e9-85fa-3a3666d60344.png)

4. Received to alertmanager:
![image](https://user-images.githubusercontent.com/33157540/59770560-f1caa600-92b0-11e9-947e-1b1de63fe55b.png)
5. But in alerta a see only one alert, and it wrong
![image](https://user-images.githubusercontent.com/33157540/59770628-11fa6500-92b1-11e9-9fed-e247010f34ec.png)
![image](https://user-images.githubusercontent.com/33157540/59770719-32c2ba80-92b1-11e9-99a0-3eaa1b9cd249.png)

**Expected behavior**
Two alerts with right labels
