### ISSUE TITLE
Heartbeats show up as (closed) alerts in reports and on the alert dashboard itself.

### ISSUE THREAD

**Issue by darkl0rd** [alerta/alerta#1076]
**Issue Summary**
Using Prometheus' AlertManager to send a Heartbeat using the following Alert definition:
```
groups:
- name: Alerta
  rules:
  - alert: Heartbeat
    expr: vector(1)
    labels:
      severity: informational
      timeout: 300
```

The alerta container is running with the following environment variables set (only showing relevant ones):
```
  PLUGINS: "prometheus,heartbeat"
  INSTALL_PLUGINS: "prometheus,heartbeat"
```

In the Alerta Dashboard, Heartbeats are correctly displayed under the "Heartbeats" item.
However, on the Alert dashboard itself, they are also visible as actual "alerts", when toggling the filter to show "closed" alerts.
In addition, they also show up in "Reports" under "Top Offenders" and "Top Standing".

**Environment**
- OS: Linux
- API version: latest
- Deployment: Docker
- Database: [Postgres
- Server config:
  - Auth enabled? Yes
  - Auth provider? Basic
  - Customer views? No
- web UI version: latest
- CLI version: latest

**To Reproduce**
See summary.

**Expected behavior**
The alertmanager Heartbeat alert to be turned into a "heartbeat" and not also show up as an alert.
