### ISSUE TITLE
Attribute not rendered as link with prometheus alert

### ISSUE THREAD

**Issue by michael-doubez** [alerta/alerta#1123]
**Issue Summary**

Using an URL as an attribute (actually a prometheus annotation), I was expecting the attribute to be rendered as as link because of comment in #870 

> This is already possible by passing the URL to any external system as an alert attribute. It will be rendered clickable in the web UI and should open a new tab.

**Environment**
- OS: Linux
 API version: 7.4.0
- Deployment:self-hosted
- WSGI environment: nginx/uwsgi

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? GitHub
  Customer views? No

- web UI version:7.4.0
- CLI version: 7.4.0

**To Reproduce**
1. Define an alert in Prometheus

```
alert: AlertIt
expr: vector(1)
labels:
  service: Test
  severity: error
  timeout: "60"
annotations:
  description: This is a test
  link_it: http://go/for/it
```

2. Forward the alert to alerta in alertmanager
3. Open alert detail
4. The field link_it is not a link with raw data

```
{
  "status": "firing",
  "labels": {
    "alertname": "AlertIt",
    "service": "Test"
    "severity": "error"
  },
  "annotations": {
    "linki_it": "http://go/for/it",
    "description": "This is a test",
  },
  "startsAt": "2020-01-13T03:02:18.59713857+01:00",
  "endsAt": "0001-01-01T00:00:00Z",
  "generatorURL": ...",
  "fingerprint": "d8ce97e93f829c67"
}
```

**Expected behavior**

I wanted to be able to click on the link in order to access details or playbook.

**Additional context**

I have not tried with a curl command to see if it is specific to prometheus.
