### ISSUE TITLE
heartbeat timeout dont get from alert labels

### ISSUE THREAD

**Issue by proffust** [alerta/alerta#1401]
alert in prometheus
```yaml
groups:
- name: targets
  rules:
  - alert: DeadMansSwitch
    expr: vector(1)
    labels:
      severity: critical
      event: Heartbeat
      timeout: 1800
      monitor: nop_m10_collector
    annotations:
      description: This is a DeadMansSwitch meant to ensure that the entire Alerting pipeline
        is functional.
      summary: Alerting DeadMansSwitch
```

created heartbeat 
```
    {
      "attributes": {
        "environment": "Production", 
        "group": "Prometheus", 
        "service": [
          ""
        ], 
        "severity": "critical"
      }, 
      "createTime": "2020-12-01T21:15:24.964Z", 
      "customer": null, 
      "href": "http://metrics.sys.local/alerta/api/heartbeat/1c1103ba-ac24-4eab-95f6-bc5557d62536", 
      "id": "1c1103ba-ac24-4eab-95f6-bc5557d62536", 
      "latency": 0, 
      "maxLatency": 2000, 
      "origin": "prometheus/nop_m10_collector", 
      "receiveTime": "2020-12-01T21:15:24.964Z", 
      "since": 459, 
      "status": "ok", 
      "tags": [
        "alertname=DeadMansSwitch", 
        "collector=nop_m10_collector", 
        "timeout=1800"
      ], 
      "timeout": 86400, 
      "type": "Heartbeat"
    }
```
