### ISSUE TITLE
build: review github action workflows and simplify

### ISSUE THREAD

**Issue by satterly** [alerta/alerta#1623]
Use workflow reuse and dependency chaining https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

Example

docker-alerta/.github/workflows/docker.yml
```
name: Push to DockerHub

on:
  push:
    tags:
      - v*

env:
  REPOSITORY_URL: registry.hub.docker.com
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  test:
    uses: alerta/docker-alerta/.github/workflows/test.yml@master
    secrets: 
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  push:
    ...
```

docker-alerta/.github/workflows/test.yml
```
name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
    tags:
      - 'v*'
  workflow_call:
    secrets:
      DOCKERHUB_TOKEN:
        required: true
```
