### ISSUE TITLE
Customer views - can't login - NoCustomerMatch - Keycloak

### ISSUE THREAD

**Issue by oijkn** [alerta/alerta#1632]
**Issue Summary**
Customers Keycloak roles do not match.

**Environment**
- OS: CentOS 7
- API version: 8.5.0
- Deployment: Docker

- Database: Postgres

- Server config:
  Auth enabled: Yes
  Auth provider: Keycloack
  Customer views: Yes

- web UI version: 8.5.0
- CLI version: 8.5.0

**To Reproduce**
1. Follow the [official doc](https://docs.alerta.io/authentication.html?highlight=auth_provider#keycloak-oauth2) to configure Keycloak client.
2. Then add new Keycloak role in the Customers menu
3. Try lo loggin with customer account
4. See error: No customer lookup configured for user '-----' or '-----.com' (403)

**Expected behavior**
I expect that the user can identify with the group configured in Keycloak

**Screenshots**
##### Keycloack config:
![image](https://user-images.githubusercontent.com/18188407/143847737-d4a0ee92-3590-451f-8bdf-22bea8a2eb73.png)

##### Alerta Customers config:
![image](https://user-images.githubusercontent.com/18188407/143848182-7dde49ca-8ca9-4afb-a1c1-969fcb373ca1.png)

**Alertad Docker config**
```yaml
    environment:
      # - DEBUG=True  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io
      - ADMIN_PASSWORD=alerta # default is "alerta"
      - ADMIN_KEY=demo-key  # assigned to first user in ADMIN_USERS
      - PLUGINS=remote_ip,reject,heartbeat,blackout,normalise,prometheus

      - http_proxy=http://xxx.xxx.xxx.xxx:80
      - https_proxy=http://xxx.xxx.xxx.xxx:80

      - CUSTOMER_VIEWS=True

      - AUTH_PROVIDER=keycloak
      - KEYCLOAK_URL=https://my-keycloak-url.com
      - KEYCLOAK_REALM=my_realm
      - OAUTH2_CLIENT_ID=demo-alerta
      - OAUTH2_CLIENT_SECRET=********
      - ALLOWED_KEYCLOAK_ROLES=admin,guest,user,alerta-devops,alerta-kpi,alerta-mco

      - USE_PROXYFIX=True # use if proxy is terminating HTTPS traffic
      - ALLOWED_ENVIRONMENTS=Production,Development,Code,None,Acceptation
      - SIGNUP_ENABLED=False
```

However, it works if I manually configure the client name with the keycloak role name.

**Comment by satterly** [comment]
What is your `roles` claim called? It defaults to "roles" but you may need to set it like this ...

```
OIDC_ROLE_CLAIM = "my-custom-roles-claim"
```

**Comment by oijkn** [comment]
> What is your `roles` claim called ?

The names of the roles are those shown on the screenshots: `alerta-devops`, `alerta-mco` and `alerta-kpi`.
I am currently trying to connect a client in the `alerta-devops` role.

I have added the following configuration but without success: `- OIDC_ROLE_CLAIM=alerta-devops`

**Comment by satterly** [comment]
They are the names of your roles. I asked what was the name of your "role claim". In the tests for Keycloak you can see that the name of the "role claim" is "role" ...

https://github.com/alerta/alerta/blob/5623da6c548e926d5c4298b6ccdb949e05c9ffda/tests/test_providers.py#L1318-L1323

And that the "roles" listed are "devops", "alerta-project" etc which are similar to yours such as "alerta-devops" etc.

I suspect you haven't configured Keycloak to send the role claim with the JWT access token response or the userinfo response.

**Comment by oijkn** [comment]
I think the configuration is ok on the Keycloack side, right ?

![image](https://user-images.githubusercontent.com/18188407/143861941-003f3b87-749e-4e39-be2f-66651c2dadad.png)

**Comment by satterly** [comment]
Looks reasonable. Check the JWT token received by the web UI. See this comment for how ... https://github.com/alerta/alerta/issues/1073#issuecomment-530072872

**Comment by oijkn** [comment]
> Looks reasonable. Check the JWT token received by the web UI. See this comment for how ... #1073 (comment)

I followed the instructions following your link but unfortunately I can't get the Authorization key from the Headers.
![image](https://user-images.githubusercontent.com/18188407/143880039-02b197c3-f67a-4713-82d5-6fa46842c8c9.png)

And I always get this error message when I try to connect using Keycloak
![image](https://user-images.githubusercontent.com/18188407/143880858-7f15d5b1-64a7-4ea0-a583-cdd2a0bf5ece.png)

**Comment by satterly** [comment]
Sorry to troubleshoot this you'll need to disable `CUSTOMER_VIEWS` login, get the token, and decode it. You can re-enabled customer views once you've worked out why the roles mapping isn't working.

**Comment by oijkn** [comment]
Thanks for the help, I can decode the JWT but I don't see my roles in the `roles` key :

```json
{
  "iss": "http://xxx.xxx.xxx.xxx/api/",
  "typ": "Bearer",
  "sub": "*******",
  "aud": "demo-alerta",
  "exp": 1639405581,
  "nbf": 1638195981,
  "iat": 1638195981,
  "jti": "*******",
  "name": "*******",
  "preferred_username": "*******",
  "email": "*******",
  "provider": "keycloak",
  "roles": [
    "*******",
    "*******",
    "*******",
    "*******",
    "*******",
    "*******"
  ],
  "scope": "read write",
  "email_verified": false
}
```

**Comment by satterly** [comment]
Where do the roles that you have "*" out come from? Find out where they are being mapped from and perhaps you need to do something similar for your roles.

**Comment by oijkn** [comment]
I'm trying to apply the same configuration as the other elements in the key rules ("*******"). I'll get back to you as soon as I have something new.

**Comment by oijkn** [comment]
By applying the same configuration in Keycloak for the roles "*******" now I have my role `alerta-devops` which appears but impossible to log in
```json
  "roles": [
    "*******",
    "*******",
    "*******",
    "*******",
    "*******",
    "*******"
    "alerta-devops"
  ],
```

**Comment by satterly** [comment]
You're going to have to define "impossible to log in". And perhaps this discussion could move to [Slack](https://slack.alerta.dev) where it would be easier to troubleshoot.

**Comment by oijkn** [comment]
I try to debug the python code on my side to understand where the problem can come from.
If I refer to your [code](https://github.com/alerta/alerta/blob/5623da6c548e926d5c4298b6ccdb949e05c9ffda/alerta/database/backends/postgres/base.py#L1380), the `match` variable returns the name of the user (**user-devops** for example).
And the postgres query `SELECT customer FROM customers WHERE match=%s` returns the same as the `alerta --profile alerta customers` command.

![image](https://user-images.githubusercontent.com/18188407/144022431-576ff4dc-1474-48d7-b578-7bdd80b22ce8.png)

So the match is never made because you compare a login with a customer name or there is something more complex that I do not see.

**Comment by satterly** [comment]
It's a loop. https://github.com/alerta/alerta/blob/5623da6c548e926d5c4298b6ccdb949e05c9ffda/alerta/database/backends/postgres/base.py#L1385 

It should try to match login and any groups.

**Comment by oijkn** [comment]
Yes I understand that it' a loop and here is the trace of the debug in the logs (I modified the code for the debug)

```
2021-11-30 10:21:38,711 alerta.app[45]: [DEBUG] $login = "user-devops" --- $matches = "user-devops" request_id=c8d70ac6-d22c-4a5e-9002-2b3b8f0e0aac ip=xxx.xxx.xxx.xxx
2021-11-30 10:21:38,711 alerta.app[45]: [DEBUG] ****************************************
$query = SELECT customer FROM customers WHERE match='user-devops' LIMIT 50 OFFSET 0
**************************************** request_id=c8d70ac6-d22c-4a5e-9002-2b3b8f0e0aac ip=xxx.xxx.xxx.xxx

2021-11-30 10:21:38,712 DEBG 'uwsgi' stdout output:
2021-11-30 10:21:38,712 alerta.app[45]: [DEBUG] $response = "[]" request_id=c8d70ac6-d22c-4a5e-9002-2b3b8f0e0aac ip=xxx.xxx.xxx.xxx
2021-11-30 10:21:38,712 alerta.app[45]: [DEBUG] $login = "user-devops" --- $matches = "myrealm.com" request_id=c8d70ac6-d22c-4a5e-9002-2b3b8f0e0aac ip=xxx.xxx.xxx.xxx
2021-11-30 10:21:38,712 alerta.app[45]: [DEBUG] ****************************************
$query = SELECT customer FROM customers WHERE match='myrealm.com' LIMIT 50 OFFSET 0
**************************************** request_id=c8d70ac6-d22c-4a5e-9002-2b3b8f0e0aac ip=xxx.xxx.xxx.xxx

2021-11-30 10:21:38,715 DEBG 'uwsgi' stdout output:
2021-11-30 10:21:38,713 alerta.app[45]: [DEBUG] $response = "[]" request_id=c8d70ac6-d22c-4a5e-9002-2b3b8f0e0aac ip=xxx.xxx.xxx.xxx
```

The loop checks the user and the realm of the email but I don't see when it checks the matching of the customer name.

**Comment by satterly** [comment]
I don't see your Keycloak groups/roles. I only see it trying to match the login and the email domain. Where are the Keycloak roles?

**Comment by oijkn** [comment]
> I don't see your Keycloak groups/roles. I only see it trying to match the login and the email domain. Where are the Keycloak roles?

The problem is there, the Keycloak groups/roles are present in the token but not in the python code.

**Comment by satterly** [comment]
Unless I can reproduce the problem I can't fix it. It only seems to happen for you so it would be my guess that it's something specific to do with your config otherwise lots of other people would be complaining also.

**Comment by oijkn** [comment]
Well I think I found a solution, in the file [alerta/auth/oidc.py](https://github.com/alerta/alerta/blob/master/alerta/auth/oidc.py) at the line [158](https://github.com/alerta/alerta/blob/master/alerta/auth/oidc.py#L158), if I add `roles` to argument in the call of the function `get_customers` then I can connect to Alerta.

On the other hand, surprisingly the code present in the docker is not identical to the one present in Github :

**In Docker**
`customers = get_customers(login, groups=[user.domain] + groups)`

**In Github**
`customers = get_customers(login, groups=groups + ([user.domain] if user.domain else []))`

**My Solution**
`customers = get_customers(login, groups=groups + roles + ([user.domain] if user.domain else []))`

**Comment by satterly** [comment]
Roles are for permissions, groups are for customers. However, if you a dead against using anything but "roles" to determine customers then just modify the following setting...

```
OIDC_GROUP_CLAIM = "roles"
```

**Comment by oijkn** [comment]
Okay, I followed your advice but I have a problem, in the docker when I run the `echo $OIDC_GROUP_CLAIM` command I have the expected value `alerta-devops`.

But when I debug the code in the file `alerta/auth/oidc.py` the variable `group_claim` ([line 122](https://github.com/alerta/alerta/blob/fa941889c4d23ebbde07ae777e1029b6bbeffcb9/alerta/auth/oidc.py#L122)) indicates : 

```
2021-12-01 08:50:26,934 alerta.app[45]: [DEBUG] $GROUP_CLAIM="groups" request_id=******-fbeb-*****-a34d-a09a2791247f ip=xxx.xxx.xxx.xxx
```

**Comment by satterly** [comment]
> We agree that normally I should have the value alerta-devops as configured in the environment variables in the docker-compose ?

No. I said to se the variable like this ...

    OIDC_GROUP_CLAIM = "roles"

... not this ...

   OIDC_GROUP_CLAIM = "alerta-devops"

And how and where are you setting the environment variable? Can you share your docker-compose.yml or whatever you are using?

**Comment by oijkn** [comment]
Ok, sorry for the confusion, I have set `OIDC_GROUP_CLAIM=roles` in my docker-compose file and it seems to be not included in the Python code.

**docker-compose.yml config**
```yaml
version: '3.1'
services:
  web:
    image: alerta/alerta-web:8.6.4
    container_name: alerta_web
    volumes:
      - /data/alerta/config/config.json:/web/config.json
      - /data/alerta/config/alerta.conf:/app/alerta.conf
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DEBUG=True

      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring

      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io
      - ADMIN_PASSWORD=alerta
      - ADMIN_KEY=demo-key

      - PLUGINS=remote_ip,reject,heartbeat,blackout,normalise,prometheus

      - CUSTOMER_VIEWS=True

      - USER_DEFAULT_SCOPES=read,write:alerts
      - GUEST_DEFAULT_SCOPES=read:alerts

      - AUTH_PROVIDER=keycloak
      - KEYCLOAK_URL=https://my-keycloack-url.com
      - KEYCLOAK_REALM=my-realm
      - OAUTH2_CLIENT_ID=alerta-ui
      - OAUTH2_CLIENT_SECRET=*******-6cf1-****-ad20-c3d6be******
      - ALLOWED_KEYCLOAK_ROLES=*

      - OIDC_GROUP_CLAIM=roles

      - SIGNUP_ENABLED=False
    restart: always
    networks:
      - alerta

  db:
    image: postgres:13.5-alpine
    container_name: alerta_db
    volumes:
      - /data/alerta/postgres_apo:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: always
    networks:
      - alerta

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_DEFAULT_EMAIL=devops@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - alerta

networks:
  alerta:
    driver: bridge
```

**Output debug oidc.py**
```sh
2021-12-01 13:34:23,048 DEBG 'uwsgi' stdout output:
2021-12-01 13:34:23,046 alerta.app[571]: [DEBUG] $ROLE_CLAIM= "roles" request_id=******-b492-4ccd-******-baf11c****** ip=xxx.xxx.xxx.xxx
2021-12-01 13:34:23,047 alerta.app[571]: [DEBUG] $GROUP_CLAIM= "groups" request_id=******-b492-4ccd-******-baf11c****** ip=xxx.xxx.xxx.xxx
2021-12-01 13:34:23,047 alerta.app[571]: [DEBUG] $CUSTOM_CLAIMS= "{'roles': ['alerta-devops'], 'groups': []}" request_id=******-b492-4ccd-******-baf11c****** ip=xxx.xxx.xxx.xxx
```
