### ISSUE TITLE
Error: failed to retrieve client config from Alerta API endpoint /api/ config

### ISSUE THREAD

**Issue by PowerSurj** [alerta/alerta#1855]
**Issue Summary**
Users get a pop-up error during login 
This issue has always been present ever since implementation
```
alerta.mydomain.com

Error: failed to retrieve client config from Alerta API endpoint /api/ config
This could be due to the API not being available, or to a missing or invalid config.json file exists, contains an "endpoint" setting and is in the same directory as the application index.html file.
```

Checking alerta nginx logs, i can see GET requests to /api/config return with code 200
https://alerta.mydomain.com/api/config
i can access the config file via WEB UI with no errors

**Environment**
- OS: Ubuntu host
- API version: Alerta Web UI 8.7.0
- Deployment: Container on Kubernetes
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Azure
  Customer views? Yes
  (or provide the `/config` endpoint output)

Helm values.yaml
```
alertaConfig:
  AUTH_REQUIRED: "True"
  CUSTOMER_VIEWS: "True"
  # audit log
  AUDIT_LOG: "True"
  AUDIT_TRAIL: "['admin','write','auth']"
  # plug-in settings
  ORIGIN_BLACKLIST: "['not-set']"
  ALLOWED_ENVIRONMENTS: "['prod','uat','test']"
  BLACKOUT_ACCEPT: "['normal','ok','cleared']"
  # webhook settings
  DEFAULT_ENVIRONMENT: "'prod'"
  # timeout settings
  ALERT_TIMEOUT: "604800"
  # web ui settings
  COLUMNS: "['severity','status','lastReceiveTime','environment','service','resource','event','value','text']"

AUTH_PROVIDER: azure

env:
  - name: DEBUG
    value: "1"
  - name: AUTH_REQUIRED
    value: "True"
  - name: AUTH_PROVIDER
    value: "azure"
  - name: CUSTOMER_VIEWS
    value: "True"
```

and the /web/config files

```
$ cat /web/config.json.example
{"endpoint": "http://localhost:8080"}

$ cat /web/config.json
{"endpoint": "/api"}

$ cat /web/config.json.j2
{"endpoint": "/api"}
```
content of the /web directory

```
$ ls -la /web
total 408
drwxrwxr-x 1 root   root   4096 Jun 16 04:58 .
drwxr-xr-x 1 root   root   4096 Jun 16 04:58 ..
-rw-rw-r-- 1 alerta root    197 Dec  6  2021 404.html
-rw-rw-r-- 1 alerta root     14 Dec  6  2021 CNAME
-rw-rw-r-- 1 alerta root   7612 Dec  6  2021 apple-touch-icon-114x114.png
-rw-rw-r-- 1 alerta root   5136 Dec  6  2021 apple-touch-icon-120x120.png
-rw-rw-r-- 1 alerta root   4768 Dec  6  2021 apple-touch-icon-144x144.png
-rw-rw-r-- 1 alerta root   8361 Dec  6  2021 apple-touch-icon-152x152.png
-rw-rw-r-- 1 alerta root   1796 Dec  6  2021 apple-touch-icon-57x57.png
-rw-rw-r-- 1 alerta root   1800 Dec  6  2021 apple-touch-icon-60x60.png
-rw-rw-r-- 1 alerta root   1795 Dec  6  2021 apple-touch-icon-72x72.png
-rw-rw-r-- 1 alerta root   2992 Dec  6  2021 apple-touch-icon-76x76.png
drwxrwxr-x 1 alerta root   4096 Dec  6  2021 audio
-rw-r--r-- 1 alerta root     21 Jun 16 04:58 config.json
-rw-rw-r-- 1 alerta root     38 Dec  6  2021 config.json.example
-rw-rw-r-- 1 root   root     21 Dec  6  2021 config.json.j2
drwxrwxr-x 1 alerta root   4096 Dec  6  2021 css
-rw-rw-r-- 1 alerta root   1186 Dec  6  2021 favicon-128.png
-rw-rw-r-- 1 alerta root    241 Dec  6  2021 favicon-16x16.png
-rw-rw-r-- 1 alerta root  14155 Dec  6  2021 favicon-196x196.png
-rw-rw-r-- 1 alerta root    319 Dec  6  2021 favicon-32x32.png
-rw-rw-r-- 1 alerta root   1597 Dec  6  2021 favicon-96x96.png
-rw-rw-r-- 1 alerta root  34494 Dec  6  2021 favicon.ico
drwxrwxr-x 1 alerta root   4096 Dec  6  2021 fonts
-rw-rw-r-- 1 alerta root   3588 Dec  6  2021 index.html
drwxrwxr-x 1 alerta root   4096 Dec  6  2021 js
-rw-rw-r-- 1 alerta root   4768 Dec  6  2021 mstile-144x144.png
-rw-rw-r-- 1 alerta root  35835 Dec  6  2021 mstile-150x150.png
-rw-rw-r-- 1 alerta root  57463 Dec  6  2021 mstile-310x150.png
-rw-rw-r-- 1 alerta root 131257 Dec  6  2021 mstile-310x310.png
-rw-rw-r-- 1 alerta root   1186 Dec  6  2021 mstile-70x70.png
```

- web UI version: 8.7.0
- CLI version: don't know

**To Reproduce**
Logging into Alerta WEB UI with Azure AD authentication enabled.

**Expected behavior**
No error pops-up
