### ISSUE TITLE
prometheus DeadMansSwitch

### ISSUE THREAD

**Issue by freeseacher** [alerta/alerta#934]
**Is your feature request related to a problem? Please describe.**
Hi!
typical heartbeat defined in prometheus world looks like 
```
alert: DeadMansSwitch
expr: vector(1)
labels:
  severity: critical
annotations:
  description: This is a DeadMansSwitch meant to ensure that the entire Alerting pipeline
    is functional.
  summary: Alerting DeadMansSwitch
```
That rule will send every repeat_interval an alert, i want to use it as heartbeats. 
but current alerta heartbeat implementation working in another way. 
Could you please add heartbeat defined like webhook with heartbeat id in get parameter so i can do it like this in alertmananeger config

```
route:
  receiver: alerta
  routes:
  - receiver: heartbeat
    repeat_interval: 2m
    match:
      alertaname: DeadMansSwitch
receivers:
- name: heartbeats
  webhook_configs:
  - send_resolved: true
    http_config:
      proxy_url: http://proxy:3128
    url: https://alerta.URL/api/webhooks/prometheus_heartbeat?api-key=KEY&heartbeat_id=myid
```
That for sure will send every 2m alert with some alert data in it. that should be ignore. The fact or receiving that alert will act as hearbeat.

The same approach used in opsgenie heartbeats https://docs.opsgenie.com/docs/heartbeat-monitoring

**Describe alternatives you've considered**
Using script with heartbeat is not acting as test script for prometheus&alertmanager pipeline. It's only checks connectivity and proxy nothing else.

**Comment by satterly** [comment]
I've come up with a more generic solution. If you send an alert with `event` of `Heartbeat` it will convert the alert into a heartbeat, and then drop the alert. Let me know what you think.

**Comment by freeseacher** [comment]
what about alert id ? after restart i'll get another alertid so it will be another heartbeat? 
what if i have several `clients` with different heartbeats but with the same alert in terms of prometheus. How should i distinct one from another?

**Comment by satterly** [comment]
>what about alert id ? after restart i'll get another alertid so it will be another heartbeat?

The alert id is irrelevant. A heartbeat is correlated by `origin`.

>what if i have several clients with different heartbeats but with the same alert in terms of prometheus. 

How should i distinct one from another?
Is the intention to heartbeat Prometheus itself or the clients that send metrics to Prometheus?

**Comment by freeseacher** [comment]
i have a repo with alerts for prometheus. 
all alerts are under its control. 
the differences between `clients` hidden in prometheus rules. for example 
`task_count{scheduler_name="discovery"} > max_task_count`
where `max_task_count` defined like 
```
groups:
  - name: XXX
    rules:
    - record: max_task_count
      expr: vectror(2000)
```

If heartbeat design will be like your approach i have two options
1. add alert rule not under git control. not so good
2. add some automation on deploy rules. for example sed alert label in DeadMansSwitch to place origin label 
may be there are any additional ways but i can't see them right now

**Comment by satterly** [comment]
I would have thought you would create a global external label for `monitor` as explained [here](https://github.com/alerta/prometheus-config#complex-example) ...
```
global:
  external_labels:
    environment: Production
    service: Prometheus
    monitor: codelab
```
If that doesn't work for you then I think your configuration probably needs something bespoke. That shouldn't stop this enhancement from being merged, though, as it would be step towards your more complete solution.

**Comment by freeseacher** [comment]
external_labels seems like good solution. maybe already used 
```
alerting:
  alert_relabel_configs:
    - target_label: client
      replacement: my_client
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
```
should work better it will not affect database setup. 
ok let me check if i can adopt an idea. 
Current issue can be closed. I'm waiting for new version to give it a try.
