### ISSUE TITLE
Alerta airgap Plugins installation

### ISSUE THREAD

**Issue by sosoriov** [alerta/alerta#958]
Is there a way to install Plugins in airgap mode?

I'm running Alerta on docker and I'm getting some errors when accessing prometheus webhook:

```
curl -XPOST  http://xxxxx:8080/api/webhooks/prometheus
```

```json
{
  "code": 400, 
  "errors": null, 
  "message": "no alerts in Prometheus notification payload", 
  "status": "error"
}
```

Thanks for your help

**Comment by satterly** [comment]
I don't understand what your issue is. You mention plugins and airgaps but then talk about the prometheus webhook and the error you quote has nothing to do with plugins. It says there are no alerts in the prometheus notification payload. Did you check the HTTP post data sent by prometheus?

And did you see this issue template when you created this issue? 

```
**Issue Summary**
A clear and concise description of what the bug is.

**Environment**
- OS: [eg. Linux, Mac, Windows]
- API version: [eg. 6.8.1]
- Deployment: [eg. Docker, Heroku, AWS, GCloud, self-hosted]
- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]

- Database: [eg. MongoDB, Postgres]

- Server config:
  Auth enabled? Yes/No
  Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
  Customer views? Yes/No
  (or provide the `/config` endpoint output)

- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....' or Run '...'
3. Scroll down to '....'
4. See error (include command output)

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.


NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.
```

I can't guess what your environment looks like and unless I know it makes it difficult to resolve issues quickly. 😢

**Comment by sosoriov** [comment]
Hey @satterly sorry about that

here you go!

**Issue Summary**
Cant receive alerts from Alertmanager. My initial thoughts were it might be related to the fact that I can't install additional plugins but i might be wrong.

**Environment**
- OS: Linux Centos 7
- Deployment: Docker image

- Database: MongoDb

- Server config:
  Auth enabled? No
  Auth provider? No
  Customer views? No


**To Reproduce**
Docker images deployment:

**MongoDB**

```
docker run --name="alerta-db" --restart=unless-stopped -v /data/mongodb:/data/db  -d myprivaterepo/docker.io/bitnami/mongodb:v4.0.6
```

**Alerta Web**

```
export DATABASE_URL=mongodb://db:27017/monitoring
docker run --name="alerta-web" --restart=unless-stopped  --link alerta-db:db \
-e DATABASE_URL=$DATABASE_URL \
-e ALERTMANAGER_API_URL="http://xxxx:9093" \
-e PLUGINS="reject,heartbeat,blackout,prometheus" \
-e INSTALL_PLUGINS="prometheus" \
-e AUTH_REQUIRED="False" \
-e DEBUG="1" \
-e ALLOWED_ENVIRONMENTS="prod,test,acpt,dvlp" \
-d -p 8080:8080 myprivaterepo/alerta/alerta-web:v7.1.0
```

error msg from Alertmanager:

```
Apr 26 11:51:34  alertmanager[158467]: level=error ts=2019-04-26T09:51:34.938441909Z caller=dispatch.go:177 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 403 from http://localhost:8080/api/webhooks/prometheus"
```

```
curl -XPOST  http://xxx:8080/api/webhooks/prometheus
{
  "code": 400,
  "errors": null,
  "message": "no alerts in Prometheus notification payload",
  "status": "error"
}
```

last lines from Alerta-Web container log:

```
2019-04-26 09:54:04,939 DEBG 'uwsgi' stdout output:
WARNING:alerta.plugins:[POLICY] Alert environment does not match one of prod, test, acpt, dvlp

2019-04-26 09:54:04,940 DEBG 'uwsgi' stdout output:
[pid: 60|app: 0|req: 881/3651] 172.17.0.1 () {36 vars in 463 bytes} [Fri Apr 26 09:54:04 2019] POST /api/webhooks/prometheus => generated 148 bytes in 4 msecs (HTTP/1.1 403) 4 headers in 140 bytes (1 switches on core 0)

2019-04-26 09:54:04,940 DEBG 'nginx' stdout output:
ip=\- [\26/Apr/2019:09:54:04 +0000] "\POST /api/webhooks/prometheus HTTP/1.1" \403 \148 "\-" "\Alertmanager/0.16.1"

2019-04-26 09:54:04,941 DEBG 'nginx' stdout output:
2019/04/26 09:54:04 [info] 49#49: *4971 client 172.17.0.1 closed keepalive connection

2019-04-26 09:54:06,004 DEBG 'uwsgi' stdout output:
[pid: 61|app: 0|req: 1516/3652] 10.211.17.67 () {44 vars in 812 bytes} [Fri Apr 26 09:54:05 2019] GET /api/alerts?sort-by=lastReceiveTime => generated 7449 bytes in 31 msecs (HTTP/1.1 200) 5 headers in 175 bytes (1 switches on core 0)

2019-04-26 09:54:06,004 DEBG 'nginx' stdout output:
ip=\- [\26/Apr/2019:09:54:06 +0000] "\GET /api/alerts?sort-by=lastReceiveTime HTTP/1.1" \200 \7449 "\http://srvpprom01.winnet.local:8080/alerts" "\Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
```

Alertmanager config

```
global:
  resolve_timeout: 5m

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    # Apply inhibition if the alertname is the same.
    equal: ['alertname']

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'default'  # default/fallback request handler
  routes: # Routes must be define by precedence
    - receiver: 'null'
      match:
        alertname: "Watchdog"
    - receiver: 'null'
      match:
        alertname: "AlertmanagerDown"
    - receiver: 'alerta'
      group_by: ['alertname']
      group_wait: 15s
      group_interval: 30s
      repeat_interval: 1m
      continue: true
      match_re:
        alertname: ".*."

receivers:
- name: "alerta"
  webhook_configs:
  - url: 'http://localhost:8080/api/webhooks/prometheus'
    send_resolved: true
- name: default
  webhook_configs:
    - url: "http://localhost:2000/dvlp"
      send_resolved: true
- name: 'null'

```

thanks for your help

**Comment by satterly** [comment]
If you look at the error messages you will see
```
WARNING:alerta.plugins:[POLICY] Alert environment does not match one of prod, test, acpt, dvlp
```
So you need to define a label called `environment` and set it to one of these values.

See the README https://github.com/alerta/prometheus-config/blob/master/README.md#configuration---rules

**Comment by sosoriov** [comment]
Do you know why I'm getting this in the interface,... i don't have any environment with "Production" value

```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    cluster: cl-prod01
    environment: prod
```
 
![2019-04-26 14_55_40-Alerts _ Alerta](https://user-images.githubusercontent.com/6907952/56809165-8249b480-6833-11e9-9ceb-b354afad116a.png)
